# docker-compose.yml
version: '3'

services:

  webapp:
    image: webapp-flask
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "whatsgoingon:project"
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
